processing/api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path("get-authors", views.get_home),
    path("add-authors/", views.post_home)
]

processing/bookpedia/urls.py
from django.urls import path

from . import views

app_name = "bookpedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:autor_id>/resultados/", views.resultados, name="resultados"),
    path("<int:livro_id>/resumo/", views.resumo, name="resumo"),
]

processing/myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('ecommerce.urls')),
]

processing/processing/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bookpedia.urls")),
    path("", include("api.urls")),
]

processing/bookpedia/models.py
from django.db import models

# Create your models here.


# Nome do livro - texto com 200 caracteres + data da publicação
class Autor(models.Model):
    nome = models.CharField(max_length=200)


# Autor - Todo livro vai estar vinculado a um autor
class Livro(models.Model):
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    nome = models.CharField(max_length=200)
    paginas = models.IntegerField(default=0, blank=True, null=True)
    resumo = models.TextField(blank=True, null=True)
    pub_date = models.DateTimeField("date published")

processing/api/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view
from bookpedia.models import Autor, Livro
from .serializers import AutorSerializer, LivroSerializer

@api_view(['GET'])
def get_home(request):
    autor = Autor.objects.all()
    serializer = AutorSerializer(autor, many=True)
    return Response(serializer.data)

@api_view(['POST'])
def post_home(request):
    serializer = AutorSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)

processing/bookpedia/views.py
from django.shortcuts import render, get_object_or_404

from .models import Livro, Autor

# Create your views here.


def index(request):
    autor_list = Autor.objects.all
    context = {"autor_list": autor_list}
    return render(request, "bookpedia/index.html", context)


def resultados(request, autor_id):
    autor = get_object_or_404(Autor, pk=autor_id)
    livros_list = autor.livro_set.all()
    context = {"livros_list": livros_list}
    return render(request, "bookpedia/resultados.html", context)


def resumo(request, livro_id):
    livro = get_object_or_404(Livro, pk=livro_id)
    context = {"livro": livro}
    return render(request, "bookpedia/resumo.html", context)

processing/bookpedia/templates/bookpedia/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Autores</title>
  </head>
  <body>
    {% if autor_list %}
    <h1>Autores</h1>
    <ul>
      {% for autor in autor_list %}
      <li>
        <a href="{% url 'bookpedia:resultados' autor.id %}">{{ autor.nome }}</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>Sem autores disponíveis.</p>
    {% endif %}
  </body>
</html>

processing/bookpedia/templates/bookpedia/resultados.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Livros</title>
  </head>
  <body>
    <h1>{{ autor.nome }}</h1>

    <ul>
      {% for livro in livros_list %}
      <li>
        <a href="{% url 'bookpedia:resumo' livro.id %}">{{ livro.nome }} -- {{ livro.paginas }} página{{ livro.paginas|pluralize }}</a>
      </li>
      {% endfor %}
    </ul>

    <a href="{% url 'bookpedia:index' %}">Retornar para autores</a>
  </body>
</html>

processing/bookpedia/templates/bookpedia/resumo.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Resumo do livro</title>
  </head>
  <body>
    <h2>Resumo de {{ livro.nome }}</h2>

    <p>{{ livro.resumo }}</p>

    <a href="{% url 'bookpedia:index' %}">Retornar para autores</a>
    {% comment %}<a href="{% url 'bookpedia:resultados' %}">Retornar para livros</a> {% endcomment %}
  </body>
</html>

processing/ecommerce/templates/ecommerce/resultados.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Livros</title>
  </head>
  <body>
    <h1>{{ autor.nome }}</h1>

    <ul>
      {% for livro in livros_list %}
      <li>
        <a href="{% url 'bookpedia:resumo' livro.id %}"
          >{{ livro.nome }} -- {{ livro.paginas }} página{{
          livro.paginas|pluralize }}</a
        >
      </li>
      {% endfor %}
    </ul>

    <a href="{% url 'bookpedia:index' %}">Retornar para autores</a>
  </body>
</html>

processing/ecommerce/templates/ecommerce/resumo.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Resumo</title>
  </head>
  <body>
    <h2>Resumo de {{ livro.nome }}</h2>

    <p>{{ livro.resumo }}</p>

    <a href="{% url 'bookpedia:index' %}">Retornar para autores</a>
    {% comment %}
    <a href="{% url 'bookpedia:resultados' %}">Retornar para livros</a> {%
    endcomment %}
  </body>
</html>